version: 2

project_name: todo
release:
  github:
    owner: dhirajzope
    name: todo-cli

builds:
  - id: todo
    main: ./main.go
    binary: todo
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - id: tar
    ids:
      - todo                      # replaces deprecated `builds` :contentReference[oaicite:0]{index=0}
    formats:
      - tar.gz                    # replaces deprecated `format` :contentReference[oaicite:1]{index=1}
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: zip
    ids:
      - todo
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: deb
    ids:
      - todo                      # replaces deprecated `builds` :contentReference[oaicite:2]{index=2}
    formats:
      - deb                       # replaces deprecated `format`
    file_name_template:          # replaces deprecated `name_template`
      "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}.deb"
    section: utils
    description: "A simple terminal-based TODO application"
    license: MIT
    maintainer: "Dhiraj Zope <dhirajzope@gmail.com>"
  - id: rpm
    ids:
      - todo
    formats:
      - rpm
    file_name_template:
      "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}.rpm"
    description: "A simple terminal-based TODO application"
    license: MIT
    maintainer: "Dhiraj Zope <dhirajzope@gmail.com>"