version: 2

project_name: todo

# This file is kept for future reference but the release process
# now uses GitHub Actions matrix builds for better platform compatibility

release:
  github:
    owner: dhirajzope
    name: todo-cli

# Note: Currently using GitHub Actions matrix builds instead of GoReleaser
# for better CGO cross-compilation support. See .github/workflows/release.yml

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'