name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 1) Native cgo build per OS/arch
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
          - os: windows-latest
            goos: windows
            goarch: arm64
    outputs:
      artifact-name: dist-${{ matrix.goos }}-${{ matrix.goarch }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'

      - name: Download dependencies
        run: go mod download

      - name: Build snapshot (cgo enabled)
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --snapshot --skip-publish
        env:
          CGO_ENABLED: '1'
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/

  # 2) Gather all artifacts + publish one GitHub Release
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # download each of the six dist folders
      - name: Download linux/amd64
        uses: actions/download-artifact@v4
        with:
          name: dist-linux-amd64
          path: dist/linux-amd64

      - name: Download linux/arm64
        uses: actions/download-artifact@v4
        with:
          name: dist-linux-arm64
          path: dist/linux-arm64

      - name: Download darwin/amd64
        uses: actions/download-artifact@v4
        with:
          name: dist-darwin-amd64
          path: dist/darwin-amd64

      - name: Download darwin/arm64
        uses: actions/download-artifact@v4
        with:
          name: dist-darwin-arm64
          path: dist/darwin-arm64

      - name: Download windows/amd64
        uses: actions/download-artifact@v4
        with:
          name: dist-windows-amd64
          path: dist/windows-amd64

      - name: Download windows/arm64
        uses: actions/download-artifact@v4
        with:
          name: dist-windows-arm64
          path: dist/windows-arm64

      - name: Consolidate dist/
        run: |
          mkdir -p dist-all
          cp -r dist/linux-*/* dist-all/
          cp -r dist/darwin-*/* dist-all/
          cp -r dist/windows-*/* dist-all/
          rm -rf dist
          mv dist-all dist

      - name: Publish GitHub Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean --skip-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
